### ISSUE TITLE
nothing is clickable

### ISSUE THREAD

**Issue by JavaWarrior** [frknbasaran/whatsapp-web-smiley-support#9]
somehow - recently - nothing is clickable when the extension is on; no links and conversation is only clickable from the far left side.
I suggest adding ` pointer-events: none; ` to the `wawss-autocomplete-wrapper` `div`.

**Comment by rizkiandrianto** [comment]
+1
Maybe you can do pull request?

Summon @frknbasaran :dancer:

**Comment by michaelzoidl** [comment]
Same here, when disabling the extension everything works fine.

**Comment by darraghmckay** [comment]
#8 
My pull request fixes this issue (although not how you suggested) 
However my pull request has been ignored for the past 3 months
